<?php

namespace App\Controller\Admin;

use App\Entity\Job;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class JobCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Job::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud->setDefaultSort(['createdAt' => 'DESC']);
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('title'),
            TextField::new('category')->onlyOnIndex(),
            AssociationField::new('category')->onlyOnForms(),
            DateField::new('expireAt')->setFormat('y-MM-dd'),
            BooleanField::new('isPublished'),
            TextEditorField::new('description')->onlyOnForms(),
            IntegerField::new('salary')->onlyOnForms(),
            ArrayField::new('tags')->onlyOnForms(),
            TextField::new('location')->onlyOnForms()
        ];
    }

    public function configureFilters(Filters $filters): Filters
    {
        return $filters->add('category')->add('isPublished');
    }

    public function configureActions(Actions $actions): Actions
    {
        return $actions->remove(Crud::PAGE_INDEX, Action::DELETE)->remove(Crud::PAGE_INDEX, Action::EDIT); // TODO: Change the autogenerated stub
    }
}
